services:
  db:
    image: postgres:15
    container_name: fuhrpark-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=fuhrpark
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: