spring.application.name=FuhrPark

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fuhrpark}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

tracking.tcp.enabled=${TRACKING_TCP_ENABLED:true}
tracking.tcp.port=${TRACKING_TCP_PORT:9090}