apiVersion: v1
kind: Service
metadata:
  name: fuhrpark
spec:
  type: NodePort
  selector:
    app: fuhrpark
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: tcp-tracking
      port: 9090
      targetPort: 9090
      nodePort: 30090
