### GET request to example server
PUT http://localhost:8080/trucks/e8e528f3-18fc-4507-ab09-d60fc95adfce
Content-Type: application/json

{
  "licensePlate" : "test",
  "brand": "test",
  "capacity": 100
}




###